# Generated by Django 4.2.2 on 2023-08-03 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installment', '0003_remove_installment_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
