# Generated by Django 4.2.2 on 2023-08-03 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installment', '0004_alter_installment_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installment',
            name='end_date',
            field=models.DateField(),
        ),
    ]
