# Generated by Django 4.2.2 on 2023-08-09 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('installment', '0006_installment_duration_alter_installment_start_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='installment',
            options={'verbose_name': 'Installment', 'verbose_name_plural': 'Installment'},
        ),
        migrations.AlterModelOptions(
            name='installmentsplans',
            options={'verbose_name': 'InstallMentsPlans', 'verbose_name_plural': 'InstallMentsPlans'},
        ),
    ]
