# Generated by Django 4.2.2 on 2023-08-22 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='user',
        ),
        migrations.AddField(
            model_name='notification',
            name='title',
            field=models.CharField(default='', max_length=55),
        ),
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.TextField(default='', max_length=255),
        ),
    ]
