# Generated by Django 4.2.2 on 2023-08-27 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0003_usermessages'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermessages',
            name='public',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='notification.notification', verbose_name='Notification'),
        ),
    ]
