# Generated by Django 4.2.2 on 2023-08-27 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0004_usermessages_public'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermessages',
            name='public',
        ),
    ]
