# Generated by Django 4.2.2 on 2023-08-01 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='provider',
            options={'managed': True, 'verbose_name': 'Provider', 'verbose_name_plural': 'Providers'},
        ),
        migrations.AlterModelTable(
            name='provider',
            table='',
        ),
    ]
