# Generated by Django 4.2.2 on 2023-08-13 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OnBoarding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='onBoarding/')),
            ],
            options={
                'verbose_name': 'OnBoarding',
                'verbose_name_plural': 'OnBoarding',
            },
        ),
    ]
