# Generated by Django 4.2.2 on 2023-08-13 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='onboarding',
            name='desc_ar',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='onboarding',
            name='desc_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='onboarding',
            name='title_ar',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='onboarding',
            name='title_en',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
