# Generated by Django 4.2.2 on 2023-08-13 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_onboarding_desc_ar_onboarding_desc_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OffersSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='offersSliders/')),
            ],
            options={
                'verbose_name': 'OffersSlider',
                'verbose_name_plural': 'OffersSlider',
            },
        ),
    ]
