# Generated by Django 4.2.2 on 2023-08-03 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installment', '0005_alter_installment_end_date'),
        ('shop', '0003_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='plans',
            field=models.ManyToManyField(to='installment.installmentsplans'),
        ),
        migrations.DeleteModel(
            name='Price',
        ),
    ]
