# Generated by Django 4.2.2 on 2023-08-16 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_intrestedcategory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='intrestedcategory',
            options={'verbose_name': 'IntrestedCategory', 'verbose_name_plural': 'IntrestedCategory'},
        ),
    ]
