# Generated by Django 4.2.2 on 2023-08-27 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_alter_intrestedcategory_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='deposit',
            field=models.CharField(default='', max_length=55),
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('a', 'Accepted'), ('r', 'Refused'), ('p', 'Pending')], default='', max_length=1),
        ),
    ]
