# Generated by Django 4.2.2 on 2023-08-28 06:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0010_request_deposit_alter_request_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='favorits',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
