# Generated by Django 4.2.2 on 2023-08-29 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_subcategory_image_alter_request_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='deposit',
            field=models.CharField(blank=True, default='', max_length=55),
        ),
    ]
