# Generated by Django 4.2.2 on 2023-08-30 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_alter_request_deposit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intrestedcategory',
            name='category',
        ),
        migrations.AddField(
            model_name='intrestedcategory',
            name='category',
            field=models.ManyToManyField(to='shop.category', verbose_name='Category'),
        ),
    ]
