# Generated by Django 4.2.2 on 2023-09-12 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_remove_intrestedcategory_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='another_files',
            field=models.ImageField(default='', upload_to='requests/anotherFiles'),
        ),
        migrations.AddField(
            model_name='request',
            name='id_image_back',
            field=models.ImageField(default='', upload_to='requests/backId/'),
        ),
        migrations.AddField(
            model_name='request',
            name='id_image_front',
            field=models.ImageField(default='', upload_to='requests/frontId/'),
        ),
    ]
